import io
import logging
from datetime import date
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

logger = logging.getLogger(__name__)

OUTPUT_DIR = Path("output/posters")


def _get_font(size: int, bold: bool = False):
    """Get font with fallback"""
    font_names = ["arialbd.ttf" if bold else "arial.ttf"]
    for font_name in font_names:
        try:
            return ImageFont.truetype(font_name, size)
        except Exception:
            continue
    return ImageFont.load_default()


def _draw_rounded_rect(draw, xy, radius, fill=None, outline=None):
    """Draw a rounded rectangle"""
    x1, y1, x2, y2 = xy
    if fill:
        draw.rectangle([x1 + radius, y1, x2 - radius, y2], fill=fill)
        draw.rectangle([x1, y1 + radius, x2, y2 - radius], fill=fill)
        draw.pieslice([x1, y1, x1 + 2*radius, y1 + 2*radius], 180, 270, fill=fill)
        draw.pieslice([x2 - 2*radius, y1, x2, y1 + 2*radius], 270, 360, fill=fill)
        draw.pieslice([x1, y2 - 2*radius, x1 + 2*radius, y2], 90, 180, fill=fill)
        draw.pieslice([x2 - 2*radius, y2 - 2*radius, x2, y2], 0, 90, fill=fill)


def _create_gradient_background(width, height, color_top, color_bottom):
    """Create gradient background"""
    img = Image.new("RGB", (width, height))
    draw = ImageDraw.Draw(img)
    
    r1, g1, b1 = color_top
    r2, g2, b2 = color_bottom
    
    for y in range(height):
        ratio = y / height
        r = int(r1 + (r2 - r1) * ratio)
        g = int(g1 + (g2 - g1) * ratio)
        b = int(b1 + (b2 - b1) * ratio)
        draw.line([(0, y), (width, y)], fill=(r, g, b))
    
    return img


def create_beautiful_monthly_poster(stats: dict) -> str:
    """
    Create a beautiful monthly poster with modern design
    
    Args:
        stats: Dictionary with keys: poop_count, sleep_score, continuous_days, beat_users, trend
        
    Returns:
        Base64 encoded PNG image string
    """
    logger.info("Creating beautiful monthly poster...")
    
    width, height = 600, 900
    img = _create_gradient_background(width, height, (102, 126, 234), (118, 75, 162))
    draw = ImageDraw.Draw(img)
    
    # Header section with white card
    header_y = 40
    _draw_rounded_rect(draw, (30, header_y, 570, header_y + 140), 20, fill="white")
    
    title_font = _get_font(36, bold=True)
    subtitle_font = _get_font(18)
    date_font = _get_font(16)
    
    draw.text((50, header_y + 25), "Monthly Report", fill=(102, 126, 234), font=title_font)
    draw.text((50, header_y + 75), "Your Health Statistics", fill=(150, 150, 150), font=subtitle_font)
    draw.text((50, header_y + 105), f"{date.today().strftime('%B %Y')}", fill=(120, 120, 120), font=date_font)
    
    # Stats cards with icons (using emoji-like symbols)
    card_y = 200
    card_height = 100
    card_spacing = 15
    stat_font = _get_font(28, bold=True)
    label_font = _get_font(16)
    
    stats_data = [
        ("Poop Count", f"{stats.get('poop_count', 0)} times", (255, 107, 107), "\u26a0"),
        ("Sleep Score", f"{stats.get('sleep_score', 0)} pts", (78, 205, 196), "\u2606"),
        ("Streak Days", f"{stats.get('continuous_days', 0)} days", (255, 165, 0), "\u2728"),
        ("Beat Users", f"{stats.get('beat_users', 0)}%", (46, 204, 113), "\u2713"),
    ]
    
    for i, (label, value, color, icon) in enumerate(stats_data):
        cy = card_y + i * (card_height + card_spacing)
        
        # Card background
        _draw_rounded_rect(draw, (30, cy, 570, cy + card_height), 15, fill="white")
        
        # Left color bar
        draw.rectangle([30, cy, 45, cy + card_height], fill=color)
        
        # Icon circle
        icon_cy = cy + card_height // 2
        draw.ellipse([60, icon_cy - 25, 110, icon_cy + 25], fill=color + (40,))
        icon_font = _get_font(24)
        draw.text((72, icon_cy - 12), icon, fill="white", font=icon_font)
        
        # Label and value
        draw.text((130, cy + 25), label, fill=(100, 100, 100), font=label_font)
        draw.text((130, cy + 55), value, fill=color, font=stat_font)
    
    # Trend section
    trend_y = card_y + len(stats_data) * (card_height + card_spacing) + 20
    _draw_rounded_rect(draw, (30, trend_y, 570, trend_y + 80), 15, fill="white")
    
    trend_title_font = _get_font(18, bold=True)
    trend_value_font = _get_font(22)
    draw.text((50, trend_y + 15), "7-Day Trend", fill=(80, 80, 80), font=trend_title_font)
    
    trend_values = stats.get("trend", [1, 2, 3, 4, 5, 6, 7])
    trend_text = "  ".join(str(x) for x in trend_values)
    draw.text((50, trend_y + 45), trend_text, fill=(102, 126, 234), font=trend_value_font)
    
    # Footer
    footer_font = _get_font(14)
    draw.text((300, height - 40), "Generated by Girl Backend", fill=(200, 200, 220), font=footer_font)
    
    # Save to file and convert to base64
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = date.today().strftime("%Y%m%d_%H%M%S")
    filename = f"monthly_{timestamp}.png"
    filepath = OUTPUT_DIR / filename
    
    img.save(filepath, "PNG")
    logger.info(f"Poster saved to: {filepath}")
    
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    base64_str = __import__("base64").b64encode(buffer.getvalue()).decode("utf-8")
    
    logger.info(f"Beautiful monthly poster generated successfully")
    return base64_str


def create_beautiful_couple_poster(info: dict) -> str:
    """
    Create beautiful couple sync report poster
    
    Args:
        info: Dictionary with couple info (sync_rate, bind_days, common_days, period_overlap)
        
    Returns:
        Base64 encoded PNG image string
    """
    logger.info("Creating beautiful couple poster...")
    
    width, height = 600, 800
    img = _create_gradient_background(width, height, (255, 107, 107), (255, 142, 171))
    draw = ImageDraw.Draw(img)
    
    # Header
    header_y = 40
    _draw_rounded_rect(draw, (30, header_y, 570, header_y + 140), 20, fill="white")
    
    title_font = _get_font(36, bold=True)
    subtitle_font = _get_font(18)
    
    draw.text((50, header_y + 35), "Couple Sync Report", fill=(255, 107, 107), font=title_font)
    draw.text((50, header_y + 85), "Your Relationship Health", fill=(150, 150, 150), font=subtitle_font)
    
    # Stats cards
    card_y = 210
    card_height = 110
    card_spacing = 18
    
    sync_rate = info.get("sync_rate", 0) if info else 0
    bind_days = info.get("bind_days", 0) if info else 0
    common = info.get("common_days", 0) if info else 0
    overlap = info.get("period_overlap", 0) if info else 0
    
    stats_data = [
        ("Sync Rate", f"{sync_rate}%", (255, 107, 107), "\u2764"),
        ("Bound Together", f"{bind_days} days", (255, 159, 243), "\u2665"),
        ("Shared Records", f"{common} days", (173, 216, 230), "\u2709"),
        ("Period Sync", f"{overlap} days", (255, 182, 193), "\u2648"),
    ]
    
    stat_font = _get_font(28, bold=True)
    label_font = _get_font(16)
    
    for i, (label, value, color, icon) in enumerate(stats_data):
        cy = card_y + i * (card_height + card_spacing)
        
        _draw_rounded_rect(draw, (30, cy, 570, cy + card_height), 15, fill="white")
        draw.rectangle([30, cy, 45, cy + card_height], fill=color)
        
        icon_cy = cy + card_height // 2
        draw.ellipse([60, icon_cy - 25, 110, icon_cy + 25], fill=color + (40,))
        icon_font = _get_font(24)
        draw.text((72, icon_cy - 12), icon, fill="white", font=icon_font)
        
        draw.text((130, cy + 28), label, fill=(100, 100, 100), font=label_font)
        draw.text((130, cy + 58), value, fill=color, font=stat_font)
    
    # Save and encode
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = date.today().strftime("%Y%m%d_%H%M%S")
    filename = f"couple_{timestamp}.png"
    filepath = OUTPUT_DIR / filename
    
    img.save(filepath, "PNG")
    logger.info(f"Couple poster saved to: {filepath}")
    
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    base64_str = __import__("base64").b64encode(buffer.getvalue()).decode("utf-8")
    
    logger.info("Beautiful couple poster generated successfully")
    return base64_str


def create_beautiful_badge_poster(badge: dict) -> str:
    """
    Create beautiful badge showcase poster
    
    Args:
        badge: Dictionary with badge info (name, rarity, icon, earned_at)
        
    Returns:
        Base64 encoded PNG image string
    """
    logger.info("Creating beautiful badge poster...")
    
    width, height = 600, 700
    img = _create_gradient_background(width, height, (255, 215, 0), (255, 165, 0))
    draw = ImageDraw.Draw(img)
    
    # Header
    header_y = 40
    _draw_rounded_rect(draw, (30, header_y, 570, header_y + 100), 20, fill="white")
    
    title_font = _get_font(36, bold=True)
    draw.text((50, header_y + 30), "Badge Showcase", fill=(255, 165, 0), font=title_font)
    
    # Badge display area
    badge_y = 170
    _draw_rounded_rect(draw, (50, badge_y, 550, badge_y + 350), 25, fill="white")
    
    if badge:
        icon = badge.get("icon", "\U0001f3c6") or "\U0001f3c6"
        name = badge.get("name", "Unknown Badge")
        rarity = badge.get("rarity", "Common")
        earned_at = badge.get("earned_at", "")
        
        # Large icon display
        icon_font = _get_font(120)
        icon_center_x = 300
        icon_center_y = badge_y + 120
        draw.text((icon_center_x - 40, icon_center_y - 50), icon, fill=(255, 215, 0), font=icon_font)
        
        # Badge name
        name_font = _get_font(32, bold=True)
        name_bbox = draw.textbbox((0, 0), name, font=name_font)
        name_width = name_bbox[2] - name_bbox[0]
        draw.text((icon_center_x - name_width//2, badge_y + 240), name, fill=(50, 50, 50), font=name_font)
        
        # Rarity badge
        rarity_colors = {
            "Common": (169, 169, 169),
            "Rare": (0, 191, 255),
            "Epic": (148, 0, 211),
            "Legendary": (255, 69, 0),
        }
        rarity_color = rarity_colors.get(rarity, (169, 169, 169))
        
        rarity_font = _get_font(24, bold=True)
        rarity_text = f"[{rarity}]"
        rarity_bbox = draw.textbbox((0, 0), rarity_text, font=rarity_font)
        rarity_width = rarity_bbox[2] - rarity_bbox[0]
        draw.text((icon_center_x - rarity_width//2, badge_y + 290), rarity_text, fill=rarity_color, font=rarity_font)
        
        # Earned date
        if earned_at:
            date_font = _get_font(16)
            draw.text((icon_center_x - 60, badge_y + 330), f"Earned: {earned_at}", fill=(120, 120, 120), font=date_font)
    
    # Save and encode
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = date.today().strftime("%Y%m%d_%H%M%S")
    filename = f"badge_{timestamp}.png"
    filepath = OUTPUT_DIR / filename
    
    img.save(filepath, "PNG")
    logger.info(f"Badge poster saved to: {filepath}")
    
    buffer = io.BytesIO()
    img.save(buffer, format="PNG")
    base64_str = __import__("base64").b64encode(buffer.getvalue()).decode("utf-8")
    
    logger.info("Beautiful badge poster generated successfully")
    return base64_str
