"""
徽章配置表
"""
from datetime import date
from typing import Dict, Any

BADGES_CONFIG: Dict[str, Dict[str, Any]] = {
    "first_poop": {
        "id": "first_poop",
        "name": "初次体验",
        "icon": "🌟",
        "rarity": "common",
        "category": "first",
        "description": "首次记录拉屎，开启健康之旅！",
        "condition_type": "first_record",
        "condition_value": {"record_type": "poop"},
    },
    "first_sleep": {
        "id": "first_sleep",
        "name": "初次安眠",
        "icon": "😴",
        "rarity": "common",
        "category": "first",
        "description": "首次记录睡眠",
        "condition_type": "first_record",
        "condition_value": {"record_type": "sleep"},
    },
    "first_period": {
        "id": "first_period",
        "name": "初见红",
        "icon": "🌸",
        "rarity": "common",
        "category": "first",
        "description": "首次记录经期",
        "condition_type": "first_record",
        "condition_value": {"record_type": "period"},
    },
    "first_water": {
        "id": "first_water",
        "name": "第一杯水",
        "icon": "💧",
        "rarity": "common",
        "category": "first",
        "description": "首次记录喝水",
        "condition_type": "first_record",
        "condition_value": {"record_type": "water"},
    },
    "first_mood": {
        "id": "first_mood",
        "name": "心情初记",
        "icon": "😊",
        "rarity": "common",
        "category": "first",
        "description": "首次记录心情",
        "condition_type": "first_record",
        "condition_value": {"record_type": "mood"},
    },
    "continuous_7": {
        "id": "continuous_7",
        "name": "初露锋芒",
        "icon": "🔥",
        "rarity": "common",
        "category": "continuous",
        "description": "连续记录7天",
        "condition_type": "continuous_days",
        "condition_value": 7,
    },
    "continuous_30": {
        "id": "continuous_30",
        "name": "持之以恒",
        "icon": "🔥🔥",
        "rarity": "rare",
        "category": "continuous",
        "description": "连续记录30天",
        "condition_type": "continuous_days",
        "condition_value": 30,
    },
    "continuous_100": {
        "id": "continuous_100",
        "name": "百日达人",
        "icon": "🔥🔥🔥",
        "rarity": "epic",
        "category": "continuous",
        "description": "连续记录100天",
        "condition_type": "continuous_days",
        "condition_value": 100,
    },
    "continuous_365": {
        "id": "continuous_365",
        "name": "一年之约",
        "icon": "🏆",
        "rarity": "legendary",
        "category": "continuous",
        "description": "连续记录365天",
        "condition_type": "continuous_days",
        "condition_value": 365,
    },
    "poop_7": {
        "id": "poop_7",
        "name": "排便达人",
        "icon": "💩",
        "rarity": "common",
        "category": "count",
        "description": "记录拉屎7次",
        "condition_type": "record_count",
        "condition_value": {"record_type": "poop", "count": 7},
    },
    "poop_50": {
        "id": "poop_50",
        "name": "排便大师",
        "icon": "💩💩",
        "rarity": "rare",
        "category": "count",
        "description": "记录拉屎50次",
        "condition_type": "record_count",
        "condition_value": {"record_type": "poop", "count": 50},
    },
    "poop_100": {
        "id": "poop_100",
        "name": "排便宗师",
        "icon": "💩💩💩",
        "rarity": "epic",
        "category": "count",
        "description": "记录拉屎100次",
        "condition_type": "record_count",
        "condition_value": {"record_type": "poop", "count": 100},
    },
    "water_30": {
        "id": "water_30",
        "name": "水润达人",
        "icon": "💧",
        "rarity": "common",
        "category": "count",
        "description": "记录喝水30次",
        "condition_type": "record_count",
        "condition_value": {"record_type": "water", "count": 30},
    },
    "mood_30": {
        "id": "mood_30",
        "name": "心情记录家",
        "icon": "😊",
        "rarity": "common",
        "category": "count",
        "description": "记录心情30条",
        "condition_type": "record_count",
        "condition_value": {"record_type": "mood", "count": 30},
    },
    "exercise_20": {
        "id": "exercise_20",
        "name": "运动爱好者",
        "icon": "🏃",
        "rarity": "common",
        "category": "count",
        "description": "记录运动20次",
        "condition_type": "record_count",
        "condition_value": {"record_type": "exercise", "count": 20},
    },
    "invite_1": {
        "id": "invite_1",
        "name": "初识好友",
        "icon": "🤝",
        "rarity": "common",
        "category": "invite",
        "description": "邀请1人",
        "condition_type": "invite_count",
        "condition_value": 1,
    },
    "invite_5": {
        "id": "invite_5",
        "name": "社交达人",
        "icon": "🤝🤝",
        "rarity": "rare",
        "category": "invite",
        "description": "邀请5人",
        "condition_type": "invite_count",
        "condition_value": 5,
    },
    "invite_15": {
        "id": "invite_15",
        "name": "人气王",
        "icon": "🤝🤝🤝",
        "rarity": "epic",
        "category": "invite",
        "description": "邀请15人",
        "condition_type": "invite_count",
        "condition_value": 15,
    },
}
